spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-ancient-violet-a1tigl9e-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_9hY7GIoSZPQf&sslmode=require

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true